version: '3.8'

services:
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: louisdevzz04/quickai-api:latest
    container_name: quickai-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/saved_models:/app/saved_models
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge 